# Site settings ~ Home page
title: Mrinal Soni
header-img: ./img/cover.jpeg
email: mrinals98@gmail.com

url: "https://mrinaaall.github.io/"
github_username:  mrinaaall
linkedin: https://www.linkedin.com/in/mrinaaall/

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 6
paginate_path: blog/page:num
excerpt_separator: <!--more-->
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
permalink: /blog/:title
#<link rel="stylesheet" href="{{ "/assets/css/clean-blog.css, " | prepend: site.baseurl }}"
